### ISSUE TITLE
INavigable.OnNavigatingFrom: invalid NavigationMode value

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [Windows-XAML/Template10#351]
Hi, 
I've noticed that when OnNavigatingFrom is getting called for either navigating to new page, or back -- the method receives NavigationMode.New with all other arguments from NavigatedTo event.
Is this a bug or an expected behavior?
How do I check Back navigation then? Thanks.

**Comment by JerryNixon** [comment]
This has been resolved in v1.0.9. We are already overriding nav modes so we might as well hint them to what they really are. I'll release 1.0.9 later this week.

**Comment by Viachaslau-Zinkevich** [comment]
@JerryNixon as far as I can say on nugget version 1.1.1 the problem still exists: when pressing backbutton and navigating back I still see in OnNavigatingFromAsync args.NavigationMode == New, like the page I'm actually on.
