### ISSUE TITLE
App.xaml: "BootStrapper" does not exist in the namespace "using:Template10.Common"

### ISSUE THREAD

**Issue by zangai** [Windows-XAML/Template10#5]
So I am having a problem with my App.xaml file:

```
<common:BootStrapper
    x:Class="SpoorAppT10.App"
    xmlns:common="using:Template10.Common"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:SpoorAppT10">
</common:BootStrapper>
```

Its complaining about not being able to find BootStrapper in Template10.Common, but it is inside that namespace:

```
namespace Template10.Common
{
    // BootStrapper is a drop-in replacement of Application
    // - OnInitializeAsync is the first in the pipeline, if launching
    // - OnStartAsync is required, and second in the pipeline
    // - NavigationService is an automatic property of this class
    public abstract class BootStrapper : Application
    {
```

I was hoping its a simple thing, and I'm missing something. Anyone have any ideas?

**Comment by JerryNixon** [comment]
This has been resolved in the most recent commit.

**Comment by cromica** [comment]
I still have this problem in version 1.0.4
![image](https://cloud.githubusercontent.com/assets/3382171/10448363/0b72920c-7195-11e5-9b60-edf890761a62.png)

I also have this problem on other controls:
![image](https://cloud.githubusercontent.com/assets/3382171/10448374/227c4f6a-7195-11e5-80eb-c11d0b024114.png)

I have this problem on newly created project using template10 blank

**Comment by cromica** [comment]
The problem seemed to be related to installation of the Visual Studio extension. It didn't asked for a VS restart and I immediately created a new project. Restarting VS solved my problem.

**Comment by Mike134** [comment]
I am having this issue now exactly as described 10/13/2015 in a project that did not have the issue yesterday. Template10 v 1.1.11. I have uninstalled Template10. Rebooted. Reinstalled Template10. Rebooted. No change.
 If I create a brand spanking new project, clean, rebuild then open App.xaml issue is in new project as well.
![capture](https://cloud.githubusercontent.com/assets/2112582/18812265/425e525e-8294-11e6-9108-017a6483b463.PNG)

**Comment by mvermef** [comment]
Did you paste the code for the resources like that? Verify you have Template 10 v1.18 installed this is the actual project templates, where as the "library" is stable 1.11 and beta 1.12

    `<Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="Styles\Custom.xaml" />
            </ResourceDictionary.MergedDictionaries>
            
        </ResourceDictionary>
    </Application.Resources>`

**Comment by dg2k** [comment]
If the project builds okay I wouldn't worry. I always get this Visual Studio spurious blue wavvy underline flags which in my experience are hit and miss (more of the latter in many cases).

If you want to get rid the wavvy lines the following helps: exit your project and delete all **bin** and **obj** folders for all projects in the solution. Finally but most importantly there is a hidden folder by the name **.vs** in the solution folder (where also the **.git** folder resides -- assuming you're using GIT). Delete the **.vs** folder. I always delete the **.vs** folder when VS acts suspiciously and things return to normal. I think this is used for caching VS settings (which will be regenerated and incrementally added to) and there comes a time when this has unintended effect. This is just speculative based on cause and effect and experience but no hard fact. Only VS team can say for sure.

**Comment by Mike134** [comment]
I have been able to narrow the issue down to a solution path issue. By moving the same solution folder and contents to different locations and opening the solution, the namespace issue would go away.
Is it Visual Studio (14.0.25431.01 u3) or Template10 (1.1.11) having the path issue, not sure yet. But I suspect VS.
Thank you for the input.

**Comment by dg2k** [comment]
> By moving the same solution folder and contents to different locations and opening the solution, the namespace issue would go away.

This would perhaps be equivalent to deleting the **.vs** folder I was referring to?? Perhaps not if you're moving the whole solution folder.  If moved the project folders instead, it could be leaving behind the **.vs** folder. But glad it worked for you.

**Comment by noumanbaloch** [comment]
I was facing the same problem but when I build the project issue gone on his own.
