### ISSUE TITLE
Project-Template Issue: x86 Release Build Config is missing "Compile with .NET Native tool chain"

### ISSUE THREAD

**Issue by robertmuehsig** [Windows-XAML/Template10#607]
When I try to create an App Package for store it will fail unless I checked the "Compile with .NET Nativ tool" on the release build configuration for x86

![image](https://cloud.githubusercontent.com/assets/756703/12776424/2346b15a-ca56-11e5-9df5-3a0d85b801aa.png)

The default Universal-Windows-Template doesn't have this issue and I just downloaded the latest version of the project template, so I guess there must be something wrong.

**Comment by robertmuehsig** [comment]
I'm not an expert in project templates, but the [this line](https://github.com/Windows-XAML/Template10/blob/master/Templates%20%28Project%29/Blank/Blank.csproj#L89) (in minimal/blank/hamburger) is wrong.

How does the Templates (Installer) actually work and how is the Template (Projects) are related to the zipped files [here](https://github.com/Windows-XAML/Template10/tree/master/Template10%20%28Installer%29/Template10.Installer/ProjectTemplates/Windows/Universal)?
If I want to fix this issue should I:
- Change the bool to true in all three templates
- zip everything
- put it in the Template (Installer) folder
  and later someone can build the actual vsix?

**Comment by MattHoppler** [comment]
Same problem with my project.

Compiler error ILT0021 Method System.Nullable Windows.Graphics.Display.DisplayInformation.get_DiagonalSizeInInches not found

**Comment by robertmuehsig** [comment]
After I enabled the .NET Native tool chain everything worked as expected - does it work for you? I don't remember the error message.

**Comment by luiscantero** [comment]
The error related to this issue is (when publishing for the store):
File '...\BundleArtifacts\Upload\x86.txt' not found.

The bad setting was inherited from the older VS project template for universal apps and was later fixed in Update 1 (if I remember correctly). The manual fix is to enable .NET Native tool chain in release mode.

Yes, we should fix this in the template that is used in the NuGet package.

**Comment by JerryNixon** [comment]
Thanks @luiscantero. It is resolved or it isn't resolved?

**Comment by luiscantero** [comment]
@JerryNixon no, it isn't fixed in T10. Like Robert mentioned above, the project templates (blank/hamburger/minimal) need to be changed like this:
&lt;UseDotNetNativeToolchain&gt;false&lt;/UseDotNetNativeToolchain&gt;
--&gt;
&lt;UseDotNetNativeToolchain&gt;true&lt;/UseDotNetNativeToolchain&gt;

**Comment by JerryNixon** [comment]
Now it is resolved.

**Comment by rfdnl** [comment]
I am very sorry everyone, but how do you guys solve this? I have posted a question somewhat related to this problem, I am still not clear on how to solve this? 

http://stackoverflow.com/questions/36051980/how-to-generate-appxupload-file/36052613#36052613

**Comment by robertmuehsig** [comment]
Regarding this issue: The project template was wrong. The issue was resolved when the user enabled the .NET Native tool chain:
![image](https://cloud.githubusercontent.com/assets/756703/13843704/9d6547d4-ec35-11e5-922a-ca323479f3e9.png)
In your case the .NET Native tool chain is already active, but something is missing, but I have no clue what.

**Comment by rfdnl** [comment]
Hi there Robert, I have already solved it :D It seems that I just have to update the Visual Studio. So that I can change the Target Version to 10586.  

```
On Thursday, March 17, 2016 6:46 PM, Robert Muehsig <notifications@github.com> wrote:
```

 Regarding this issue: The project template was wrong. The issue was resolved when the user enabled the .NET Native tool chain:

In your case the .NET Native tool chain is already active, but something is missing, but I have no clue what. —
