### ISSUE TITLE
WACK App Prelaunch Test fails in 1.1.8

### ISSUE THREAD

**Issue by artfuldev** [Windows-XAML/Template10#743]
Any app built in Release with T10 with .NET Native fails the Windows App Certification Kit (WACK) App Prelaunch Test. Used to work in 1.1.4, I made a direct jump to 1.1.8, so can't comment on other versions.

**Comment by arpadbarta** [comment]
I have mentioned this in #725 , that the Prelaunch issue was present in all versions above 1.1.4.

**Comment by ktd12** [comment]
I am still using v1.1.4 and Prelaunch works just fine.

**Comment by artfuldev** [comment]
That's the point. It works in 1.1.4. I can confirm that. Also with versions higher than 1.1.4, I'm facing more crashes. Possibly due to the Rx inclusions as mentioned in #725.

**Comment by Opiumtm** [comment]
@kenshinthebattosai it does not fail. Today I published beta version of app, no WACK errors, latest T10 version from nuget. I can notice a major performance degradation when app is compiled in release mode with .NET Native ARM. But I doesn't sure it's because of T10, it seems like a platform issue, looks like exceptionally poor quality of ARM native generated code. Same app deployed as debug .NET managed IL assembly perform **much** better. But it's another issue.

So, in fact WACK **does not** fail with T10 (I tested it today and successfully sent app package to the store). Maybe, it's because I do not use splash screen on startup.

**Comment by arpadbarta** [comment]
@Opiumtm  I've just run WACK on my latest build with T10 1.1.5 from nugget (also removed splash just to check) and still fails. It is possible that the issue is fixed in version 1.1.7 or 1.1.8 but unfortunately I can't use that because #725 , however, doesn't seem like...

**Comment by Opiumtm** [comment]
@barptad So, title 

> WACK App Prelaunch Test fails **in 1.1.8**

is wrong. In 1.1.8 version (current version on nuget) WACK does not fail.
I tested it with current version - it successfully pass WACK tests.

**Comment by 1iveowl** [comment]
And I just tested it today and I do get the WACK Prelaunch Test fails with 1.1.8. I did not use the Splash Screen in the test.

**Comment by 1iveowl** [comment]
I've done some more investigation looking into the crash dump. Does the following mean anyting to anyone? 

`0:005> !mrt100sos.pe -ccw 0x000001dc`ffb11c60
Exception object: 000001dcdf421f80
Exception type:   System.ArgumentException
Message:          Argument_AddingDuplicate. For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485
InnerException:   <none>
StackTrace (generated):
    IP               Function
    00007ffeeec3030e MyApp_7ffeee340000!$62_System::Collections::Generic::Dictionary$2<$0_MyApp::Models::Pages,System::__Canon>.Insert+0x29e
    00007ffeeec30570 MyApp_7ffeee340000!$62_System::Collections::Generic::Dictionary$2<$0_MyApp::Models::Pages,System::__Canon>.Add+0x10
    00007ffeeee6f639 MyApp_7ffeee340000!$0_MyApp::App.InitializeNavigation+0x29
    00007ffeeee6f844 MyApp_7ffeee340000!$0_MyApp::App.OnInitializeAsync+0x64
    00007ffeeee31289 MyApp_7ffeee340000!$61_Template10::Common::BootStrapper::<InitializeFrameAsync>d__77.MoveNext+0x119
    0000000000000001 
    00007fff0ad35fc1 SharedLibrary!System::Runtime::ExceptionServices::ExceptionDispatchInfo.Throw+0x21
    00007fff0ad36238 SharedLibrary!$13_System::Runtime::CompilerServices::TaskAwaiter.ThrowForNonSuccess+0x58
    00007fff0ad361d3 SharedLibrary!$13_System::Runtime::CompilerServices::TaskAwaiter.HandleNonSuccessAndDebuggerNotification+0x43
    00007fff0ad36187 SharedLibrary!$13_System::Runtime::CompilerServices::TaskAwaiter.ValidateEnd+0x17
    00007fff0ae7d81b SharedLibrary!$13_System::Runtime::CompilerServices::ConfiguredTaskAwaitable::ConfiguredTaskAwaiter.GetResult+0xb
    00007ffeeee31f92 MyApp_7ffeee340000!$61_Template10::Common::BootStrapper::<InternalLaunchAsync>d__53.MoveNext+0x172
`

**Comment by 1iveowl** [comment]
After spending the better part of a day debugging this issue, I think I finally tracked Down the bug and I've created PR #782 which seems to fix it.

**Comment by JerryNixon** [comment]
Resolved.

**Comment by 1iveowl** [comment]
Super. Thanks
